apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mirror
  labels:
    name: mirror
spec:
  ingreeClassName: caddy
  rules:
  - host: <your.domain.com>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <your-app>
            port:
              number: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: <your-app>
spec:
  type: ClusterIP
  selector:
    app: <your-app>
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <your-app>
  labels:
    app: <your-app>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <your-app>
  template:
    metadata:
      labels:
        app: <your-app>
    spec:
      containers:
      - name: <your-app>
        image: ghcr.io/jacexh/<your-app>:sha-70333d0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
