kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: koos
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
runtimeConfig:
  api/alpha: "false"
nodes:
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
