apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: v2fly
  annotations:
    kubernetes.io/ingress.class: caddy
  labels:
    name: v2fly
spec:
  rules:
  - host: v2fly.foobar.com
    http:
      paths:
      - pathType: Prefix
        path: "/live"
        backend:
          service:
            name: v2fly
            port:
              number: 9988
---
kind: Service
apiVersion: v1
metadata:
  name: v2fly
spec:
  type: ClusterIP
  selector:
    app: v2fly
  ports:
  - name: http
    protocol: TCP
    port: 9988
    targetPort: 9988
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2fly
  labels:
    app: v2fly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2fly
  template:
    metadata:
      labels:
        app: v2fly
    spec:
      containers:
      - name: v2fly
        image: v2fly/v2fly-core:v4.45.2
        ports:
        - containerPort: 9988
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        volumeMounts:
        - name: v2fly-config
          mountPath: /etc/v2ray
      volumes:
      - name: v2fly-config
        configMap:
          name: v2fly-config
          items:
          - key: config.json
            path: config.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: v2fly-config
data:
  config.json: |
    {
        "log": {
            "loglevel": "warning"
        },
        "inbounds": [
            {
                "port": 9988,
                "listen": "0.0.0.0",
                "protocol": "vless",
                "settings": {
                    "clients": [
                        {
                            "id": "389a0884-03b4-11ec-b72a-5254008f2fc8",
                            "email": "free@foobar.com",
                            "level": 0
                        }
                    ],
                    "decryption": "none"
                },
                "streamSettings": {
                    "network": "ws",
                    "security": "none",
                    "tlsSettings": {},
                    "tcpSettings": {},
                    "kcpSettings": {},
                    "wsSettings": {
                        "path": "/live"
                    },
                    "httpSettings": {},
                    "quicSettings": {},
                    "grpcSettings": {}
                }
            }
        ],
        "outbounds": [
            {
                "tag": "direct",
                "protocol": "freedom",
                "settings": {}
            },
            {
                "tag": "blocked",
                "protocol": "blackhole",
                "settings": {}
            }
        ],
        "routing": {
            "rules": [
                {
                    "type": "field",
                    "ip": [
                        "geoip:private"
                    ],
                    "outboundTag": "blocked"
                }
            ]
        }
    }
  client.json: |
    {
        "log": {
            "loglevel": "warning"
        },
        "inbounds": [
            {
                "listen": "127.0.0.1",
                "protocol": "socks",
                "settings": {
                    "udp": true
                },
                "port": "1080"
            },
            {
                "listen": "127.0.0.1",
                "protocol": "http",
                "settings": {
                    "timeout": 360
                },
                "port": "8080"
            }
        ],
        "outbounds": [
            {
                "mux": {
                    "enabled": false,
                    "concurrency": 8
                },
                "protocol": "vless",
                "streamSettings": {
                    "tlsSettings": {
                        "serverName": "foobar.com",
                        "allowInsecure": false
                    },
                    "security": "tls",
                    "network": "ws",
                    "wsSettings": {
                        "path": "/live"
                    }
                },
                "settings": {
                    "vnext": [
                        {
                            "address": "foobar.com",
                            "users": [
                                {
                                    "encryption": "none",
                                    "id": "389a0884-03b4-11ec-b72a-5254008f2fc8",
                                    "level": 0
                                }
                            ],
                            "port": 443
                        }
                    ]
                },
                "tag": "proxy"
            },
            {
                "tag": "direct",
                "protocol": "freedom",
                "settings": {}
            },
            {
                "tag": "blocked",
                "protocol": "blackhole",
                "settings": {}
            }
        ],
        "dns": {
            "servers": [
                "119.29.29.29",
                "114.114.114.114",
                "8.8.8.8"
            ]
        },
        "routing": {
            "strategy": "rules",
            "settings": {
                "domainStrategy": "IPIfNonMatch",
                "rules": [
                    {
                        "type": "field",
                        "ip": [
                            "0.0.0.0/8",
                            "10.0.0.0/8",
                            "100.64.0.0/10",
                            "127.0.0.0/8",
                            "169.254.0.0/16",
                            "172.16.0.0/12",
                            "192.0.0.0/24",
                            "192.0.2.0/24",
                            "192.168.0.0/16",
                            "198.18.0.0/15",
                            "198.51.100.0/24",
                            "203.0.113.0/24",
                            "::1/128",
                            "fc00::/7",
                            "fe80::/10"
                        ],
                        "outboundTag": "direct"
                    },
                    {
                        "type": "field",
                        "ip": [
                            "8.8.8.8"
                        ],
                        "outboundTag": "proxy"
                    }
                ]
            }
        }
    }
